### ISSUE TITLE
webpack-dev-server

### ISSUE THREAD

**Issue by tx4x** [dojo/web-editor#24]
Hi,
is there a some cli command to get into the dev mode ? i tried grunt webpack-dev-server but I get a warning: Cannot convert undefined or null to object Use --force to continue.

thanks for the nice example app !

**Comment by kitsonk** [comment]
Right now, what is in master, the Webpack only bundles postcss to be able to be used in a browser to be able to transpile the CSS Modules for the application.

We are working on trying to bundle the whole thing in webpack, but I am still not entirely sure the dev server will work because of some of the challenges at the moment of trying to bundle `monaco-editor`.

At the moment, you need a local web server to host the files.  Both `grunt dev` and `grunt dist` should produce builds that _should_ work from a local server and then you just need to navigate to the root of the build.

For example, if your local web server is `localhost:8080` and the parent directory of where you have `web-editor` cloned, then doing `grunt` and then navigating to `http://localhost:8080/web-editor/dev/src/` should bring up the application.

**Comment by xblox** [comment]
excellent, fully enough for me.
thanks,
g
